### ISSUE TITLE
Error: Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by ryumer** [juliancwirko/react-boilerplate#3]
`npm start` fails with below log

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/Cellar/node/4.1.2/bin/node',
> 1 verbose cli   '/usr/local/bin/npm',
> 1 verbose cli   'start' ]
> 2 info using npm@2.14.6
> 3 info using node@v4.1.2
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart react-boilerplate@0.6.1
> 6 info start react-boilerplate@0.6.1
> 7 verbose unsafe-perm in lifecycle true
> 8 info react-boilerplate@0.6.1 Failed to exec start script
> 9 verbose stack Error: react-boilerplate@0.6.1 start: `node server.js`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:818:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 10 verbose pkgid react-boilerplate@0.6.1
> 11 verbose cwd /Users/ramazanyumer/Documents/work/reactjs/react-boilerplate
> 12 error Darwin 15.3.0
> 13 error argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "start"
> 14 error node v4.1.2
> 15 error npm  v2.14.6
> 16 error code ELIFECYCLE
> 17 error react-boilerplate@0.6.1 start: `node server.js`
> 17 error Exit status 1
> 18 error Failed at the react-boilerplate@0.6.1 start script 'node server.js'.
> 18 error This is most likely a problem with the react-boilerplate package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node server.js
> 18 error You can get their info via:
> 18 error     npm owner ls react-boilerplate
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by juliancwirko** [comment]
Yeah, you right. It seems like there isn't `autoprefixer` :/ Thanks for the info. I'll try to fix it asap.

**Comment by juliancwirko** [comment]
ok you can try now. `npm update` is needed
