### ISSUE TITLE
How to use the grid system in the app?

### ISSUE THREAD

**Issue by purezen** [juliancwirko/react-boilerplate#4]

**Comment by juliancwirko** [comment]
Hi, for now you can use it the same way as it is described in the docs: http://stylusgrid.com/getting-started.html So you just need to use standard stylus files. Here is an example: https://github.com/juliancwirko/react-boilerplate/blob/master/app/components/homeView/styles.styl

**Comment by purezen** [comment]
Seems to be working now. Though, it returns `Uncaught ReferenceError: grid is not defined` where I am using `<div className={style.s-grid-top}>`

**Comment by juliancwirko** [comment]
For now you need to use camel case custom classes. I don't think it will work that way. So you need to create your own classes in the .style file like:

``` stylus
.exampleContainer
  grid(cells-align:'top')
  .exampleCell
    cell(1, 2)
```

and then in the jsx with CSS Modules:

``` jsx
(...)
<div className={style.exampleContainer}>
  <div className={style.exampleCell}>
    ...
  </div>
  <div className={style.exampleCell}>
    ...
  </div>
</div>
(...)
```

You'll find the docs on how to create custom classes here: http://stylusgrid.com/docs.html

Maybe in the future I'll try to create React-like grid component with preconfigured components or calasses, but  it is hard to tell when.
