### ISSUE TITLE
How to use Redux in the app?

### ISSUE THREAD

**Issue by purezen** [juliancwirko/react-boilerplate#5]
Hey,
Firstly, thanks for the amazing boilerplate! This is the one that has suited me after trying several ones. However, I would like to know how do I use Redux in this?

**Comment by juliancwirko** [comment]
This is a very good question. I plan to implement Redux in it soon. For now I think the best place to search for the answer is: http://redux.js.org/ and https://github.com/reactjs/react-router-redux

**Comment by purezen** [comment]
Cool! Will try to pitch in if I get the time to do it :+1:

**Comment by juliancwirko** [comment]
FYI: Redux added

**Comment by purezen** [comment]
Nice. It's much comprehensive now 👍
